knp_paginator:
    page_range: 5                       # nombre de liens de pages visibles
    default_options:
        page_name: page                 # nom du paramètre de page dans l'URL
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # ou bootstrap_v4 si tu es en Bootstrap 4
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
