version: '3.8'

services:
  # Hub Mercure
  mercure:
    image: dunglas/mercure:v0.15
    restart: unless-stopped
    environment:
      # Configuration du Hub
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'your-256-bit-secret-key-here-change-this-in-production'
      MERCURE_SUBSCRIBER_JWT_KEY: 'your-256-bit-secret-key-here-change-this-in-production'
      # Autoriser les requêtes depuis votre domaine
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3000 http://localhost:8000
        anonymous
        subscriptions
        publish_origins http://localhost:8000
    ports:
      - "3001:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  # Base de données PostgreSQL
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: symfony_app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Symfony
  symfony:
    build:
      context: ./symfony-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://symfony:symfony@database:5432/symfony_app
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3001/.well-known/mercure
      MERCURE_JWT_SECRET: 'your-256-bit-secret-key-here-change-this-in-production'
    ports:
      - "8000:80"
    depends_on:
      - database
      - mercure
    volumes:
      - ./symfony-api:/var/www/html

volumes:
  mercure_data:
  mercure_config:
  postgres_data: